Merge out of order data points before flushing to disk
nakabonne/tstorage pull request #16
Opened 2021-07-06 17:27 UTC by dpgil

This change sorts the out of order points and then merges the two slices before flushing buffered data to disk. This is a partial implementation of https://github.com/nakabonne/tstorage/issues/7 but doesn't handle points outside of the head partition bounds.

2021-07-06 17:28 UTC, dpgil commented
Hi Ryo! Let me know what you think about this change

2021-07-07 01:00 UTC, nakabonne requested changes
Hey, thank you for your contribution! This is well tested and seems like you understand how tstorage works well.

While I've left some comments, mostly they're alright.

2021-07-07 04:03 UTC, dpgil commented
@nakabonne thanks for the suggestions! I made the changes, let me know if you have any other feedback

2021-07-07 23:57 UTC, nakabonne approved these changes
LGTM. Thank you for your work!

2021-07-07 23:57 UTC, merged